server:
  port: 8081
  tomcat:
    threads:
      max: 3
    accept-count: 30

spring:
  kafka:
    bootstrap-servers: localhost:29092,localhost:29093,localhost:29094
    consumer:
      group-id: email-sender-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        auto.commit.interval.ms: "5000"
        spring.json.trusted.packages: com.errday.mailservice.mail,com.errday.mainservice.mail,*
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.errday.mailservice.mail.EmailRequest # 컨슈머가 최종적으로 변환할 타입
      enable-auto-commit: false
      max-poll-records: 500
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topic:
      dlt:
        suffix: .DLT # DLQ 토픽 접미사
    listener:
      ack-mode: RECORD
#      retry:
#        attempts: 3   # 총 시도 횟수 (최초 1 + 재시도 2)
#        interval: 1000 # 재시도 간격 (ms)
logging:
  level:
    org.apache.kafka.clients.consumer.ConsumerConfig: DEBUG
    org.apache.kafka.clients.consumer.internals.ConsumerCoordinator: DEBUG
    org.apache.kafka.clients.consumer.KafkaConsumer: DEBUG
