server:
  port: 8083
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank
    username: lecture
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true